# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['gui_app.py'],
    pathex=[
        '.',
        '下载外包续签查询',
        '下载人员变更',
        'utils',
    ],
    binaries=[],
    datas=[
        ('main.py', '.'),
        ('download_and_parse.py', '.'),
        ('renewal_order_processor.py', '.'),
        ('renewal_order_submitter.py', '.'),
        ('utils', 'utils'),
        ('下载外包续签查询', '下载外包续签查询'),
        ('下载人员变更', '下载人员变更'),
    ],
    hiddenimports=[
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'openpyxl',
        'playwright',
        'playwright.sync_api',
        'playwright.async_api',
        'playwright._impl',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'tkinter.ttk',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pip',
        'setuptools',
        'wheel',
        'email',
        'http',
        'xmlrpc',
        'pydoc',
        'unittest',
        'test',
        'lib2to3',
        'torch',
        'torchvision',
        'torchaudio',
        'scipy',
        'scipy.linalg',
        'scipy.spatial',
        'scipy.stats',
        'scipy.sparse',
        'scipy.io',
        'scipy.special',
        'scipy.optimize',
        'scipy.signal',
        'scipy.interpolate',
        'scipy.ndimage',
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.backends',
        'PIL',
        'PIL.Image',
        'sympy',
        'onnxruntime',
        'cryptography',
        'cffi',
        'jinja2',
        'lxml',
        'urllib3',
        'charset_normalizer',
        'certifi',
        'pygments',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(
    a.pure,
    level=9,
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='续签自动下单',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
